main/urls.py
from django.urls import path
from django.contrib import admin
from django.utils.translation import gettext as _

from . import views

admin.site.site_header = _("Administration page of website madaniyat.uz")
admin.site.site_title = _("Administration page of website madaniyat.uz")
admin.site.index_title = _("Home page")


urlpatterns = [

    path('', views.HomeTemplate.as_view(), name='home_template_view'),

    path('post/', views.PostList.as_view(), name='post_list'),
    path('post/<int:id>', views.PostDetail.as_view(), name='post_detail'),

    path('static/<int:id>', views.StaticDetail.as_view(), name='static_detail'),
    path('json/', views.formatJson, name='json'),

    path('application', views.ApplicationForm.as_view(), name='application_form'),
    path('contact', views.ContactPage.as_view(), name='contact_view'),

    path('person/', views.PersonList.as_view(), name='person_list'),
    path('person/<int:id>', views.PersonDetail.as_view(), name='person_detail'),

    path('regions/', views.RegionsList.as_view(), name="regions-list"),

    path('organization/', views.OrganizationList.as_view(), name='organization_list'),
    path('organization/<int:id>', views.OrganizationDetail.as_view(), name='organization_detail'),

    path('event/', views.EventList.as_view(), name='event_list'),
    path('event/<int:id>', views.EventDetail.as_view(), name='event_detail'),

    path('media/', views.MediaTemplate.as_view(), name='media_list'),

    path('media/items/', views.MediaGalleryList.as_view(), name='media_gallery_list'),
    path('media/items/<int:id>', views.MediaGalleryDetail.as_view(), name='media_gallery_detail'),

    path('statistics/', views.StatisticsList.as_view(), name='statistics_template'),
    path('search/', views.SearchTemplateView.as_view(), name='search_template'),

    path('album/', views.AlbumList.as_view(), name='album_list'),
    path('album/<int:id>', views.AlbumDetail.as_view(), name='album_detail'),

]

urlpatterns += [
    path('api/typo-report', views.TypoReportAPI.as_view(), name='typo_report_api'),
]

poll/urls.py
from django.urls import path

from . import views


app_name = 'poll'


urlpatterns = [
    path('votes/<int:poll_id>/', views.vote, name='vote'),
    path('polls/<int:poll_id>/', views.poll_view, name='poll_view'),
    path('result/<int:poll_id>/', views.result, name='result'),
]

project/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

from main import views as main_views


handler404 = main_views.NotFoundTemplateView.as_view()

urlpatterns = []

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include("poll.urls", namespace='poll')),
    prefix_default_language=True
)

urlpatterns += [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

from parler import models as parler_models


class Poll(parler_models.TranslatableModel):
    translations = parler_models.TranslatedFields(
        question=models.CharField(max_length=255, unique=True)
    )

    is_published = models.BooleanField(default=True)
    date = models.DateField(default=datetime.date.today)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Poll")
        verbose_name_plural = _("Polls")

    def __unicode__(self):
        return f"{ self.safe_translation_getter('question', self.id) }"

    def __str__(self):
        return f"{ self.safe_translation_getter('question', self.id) }"

    def get_vote_count(self):
        return Vote.objects.filter(poll=self).count()
    vote_count = property(fget=get_vote_count)

    def get_cookie_name(self):
        return 'poll_%s' % self.pk


class Item(parler_models.TranslatableModel):
    translations = parler_models.TranslatedFields(
        value=models.CharField(max_length=255, unique=True)
    )

    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

    position = models.SmallIntegerField(default=1)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Answer")
        verbose_name_plural = _("Answers")
        ordering = ['position']

    def __unicode__(self):
        return f"{ self.safe_translation_getter('value', self.id) }"

    def __str__(self):
        return f"{ self.safe_translation_getter('value', self.id) }"

    def get_vote_count(self):
        return Vote.objects.filter(item=self).count()
    vote_count = property(fget=get_vote_count)


class Vote(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, verbose_name='voted item', on_delete=models.CASCADE)
    ip = models.GenericIPAddressField(verbose_name='ip address')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Vote")
        verbose_name_plural = _("Votes")

    def __unicode__(self):
        return self.ip

    def __str__(self):
        return self.ip

poll/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render


from . import models, utils


def vote(request, poll_id):
    if request.is_ajax():

        try:
            poll = models.Poll.objects.get(translations__language_code=request.LANGUAGE_CODE, pk=poll_id)
        except models.Poll.DoesNotExist:
            return HttpResponse('Wrong parameters', status=400)

        item_id = request.GET.get("item", False)

        if not item_id:
            return HttpResponse('Wrong parameters', status=400)

        try:
            item = models.Item.objects.get(translations__language_code=request.LANGUAGE_CODE, pk=item_id)
        except:
            return HttpResponse('Wrong parameters', status=400)

        models.Vote.objects.create(
            poll=poll,
            ip=request.META['REMOTE_ADDR'],
            item=item,
        )
        response = HttpResponse(status=200)
        utils.set_cookie(response, poll.get_cookie_name(), poll_id)

        return response
    return HttpResponse(status=400)


def poll_view(request, poll_id):
    try:
        poll = models.Poll.objects.get(translations__language_code=request.LANGUAGE_CODE, pk=poll_id)
    except:
        return HttpResponse('Wrong parameters', status=400)

    try:
        items = models.Item.objects.filter(translations__language_code=request.LANGUAGE_CODE, poll=poll)
    except:
        return HttpResponse('Wrong parameters', status=400)

    context = {'poll': poll, 'items': items}

    if poll.get_cookie_name() in request.COOKIES:
        return render(request, "poll/result.html", context)
    else:
        return render(request, "poll/poll.html", context)


def result(request, poll_id):
    try:
        poll = models.Poll.objects.get(translations__language_code=request.LANGUAGE_CODE, pk=poll_id)
    except:
        return HttpResponse('Wrong parameters', status=400)

    try:
        items = models.Item.objects.filter(translations__language_code=request.LANGUAGE_CODE, poll=poll)
    except:
        return HttpResponse('Wrong parameters', status=400)

    context = {'poll': poll, 'items': items, }

    return render(request, "poll/result.html", context)


def percentage(poll, item):
    poll_vote_count = poll.get_vote_count()
    if poll_vote_count > 0:
        return float(item.get_vote_count()) / float(poll_vote_count) * 100

poll/templates/poll/base.html
{% block poll_stylesheet %}{% endblock %}
{% block poll_script %}{% endblock %}

<div id="poll-container">
    {% block poll_content %}{% endblock %}
</div>

poll/templates/poll/poll.html
{% extends "poll/base.html" %}
{% load i18n static %}


{% block poll_script %}
    <script type="text/javascript">
        var vote_url = "{% url 'poll:vote' poll.pk %}";
        var result_url = "{% url 'poll:result' poll.pk %}";

        document.addEventListener('DOMContentLoaded', function () {
            function showResults() {
                $.get(result_url, function (data) {
                    $("#poll-container").html(data);
                });
            }

            $("#poll-send").click(function () {
                var item = $('#poll-form input[name=item]:checked').val();
                if (typeof item === "undefined") {
                    alert(message.please_choose_an_answer);
                    return false;
                }
                $.get(vote_url, {item: item}, function () {
                    showResults();
                });
                return false;
            });
        });
    </script>
{% endblock %}

{% block poll_stylesheet %}
    <style type="text/css">

        .poll-container {

        }

        .poll-container .poll-style {

        }

        .poll-items {

        }

        .poll-result {
            height: auto;
        }

        .poll-items ul {

        }

        .poll-items ul li .poll-item-label {
            line-height: 2;
            margin: 0;
            vertical-align: middle;
        }

        .poll-items input[type=checkbox],
        .poll-items input[type=radio] {
            appearance: none;
            width: 20px;
            height: 20px;
            border: 2px solid orange;
            vertical-align: middle;
            position: relative;
            border-radius: 3px;
        }

        .poll-items input[type=checkbox]:checked,
        .poll-items input[type=radio]:checked {
            border-color: #fc9a06;
            padding: 5px;
            transition: .2s;
        }

        .poll-items input[type=checkbox]:checked::after,
        .poll-items input[type=radio]:checked::after {
            content: "";
            display: inline-block;
            transition: .2s;
            background: #0b5b80;
            width: 12px;
            height: 12px;
            top: 2px;
            left: 2px;
            position: absolute;
            border-radius: 2px;
            opacity: 1;
        }

    </style>
{% endblock %}


<div class="poll-container">
    {% block poll_content %}
        <form action="" method="GET" id="poll-form">

            <div class="poll-title">
                <h3>{{ poll.question }}</h3>
            </div>

            <div class="poll-items">
                <ul class="list-unstyled">

                    {% for item in items %}
                        <li>
                            <input type="radio" name="item" id="item-{{ item.id }}" value="{{ item.id }}"/>
                            <label for="item-{{ item.id }}" class="poll-item-label">{{ item.value }}</label>
                        </li>
                    {% endfor %}

                </ul>
            </div>

            <div class="poll-submit">
                <input type="button" class="poll-btn-vote thm-btn exhibhition-one__btn" id="poll-send" value="{% trans 'Vote' %}" />
            </div>

        </form>
    {% endblock %}
</div>

poll/templates/poll/result.html
{% extends "poll/base.html" %}
{% load i18n poll_tags %}


{% block poll_content %}
    <div class="poll-result">
        <div class="poll-title">
            <h3>{{ poll.question }}</h3>
        </div>

        <div class="poll-answers">
            <ul class="list-unstyled">
                {% for item in items %}
                    <li class="poll-answer my-3">
                        <span>{{ item.value }}: </span>
                        <b>{% filter floatformat %}{% percentage poll item %}{% endfilter %}%</b>
                        <br>
                        <div class="poll-answer-indicator" style="width: {% percentage poll item %}%;"></div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="poll-total-votes">
            {% trans 'Total votes' %}: <b>{{ poll.get_vote_count }}</b>
        </div>
    </div>
{% endblock %}


{% comment %}
{% extends "poll/base.html" %}

{% load i18n poll_tags %}

{% block poll_content %}

    <div class="poll-result">
        <div class="poll-title">{{ poll.question }}</div>

        <ul>
            {% for item in items %}
                <li>{{ item.value }}: <b>{% filter floatformat %}{% percentage poll item %}{% endfilter %}%</b><br>
                    <div class="indicator" style="width: {% percentage poll item %}%;"></div>
                </li>
            {% endfor %}
        </ul>

        <div class="total_votes">{% trans 'Total votes' %}: <b>{{ poll.get_vote_count }}</b></div>

        <br>

    </div>

{% endblock %}

{% block poll_stylesheet %}
    <style type="text/css">
        .indicator {
            background: green;
            border: 1px solid green;
            height: 4px;
        }

        .poll-result {
            margin: 0 auto;
            padding: 20px;
            text-align: left;
            border: 1px solid #c0c0c0;
            height: 365px;
            background-color: #ECEADD;
        }

        .poll-result ul li {
            margin: 10px 0;
        }

        .total_votes {
            float: right;
            padding-top: 10px;
        }

    </style>
{% endblock %}
{% endcomment %}