main/urls.py
from django.urls import path
from django.contrib import admin
from django.utils.translation import gettext as _

from . import views

admin.site.site_header = _("Administration page of website madaniyat.uz")
admin.site.site_title = _("Administration page of website madaniyat.uz")
admin.site.index_title = _("Home page")


urlpatterns = [

    path('', views.HomeTemplate.as_view(), name='home_template_view'),

    path('post/', views.PostList.as_view(), name='post_list'),
    path('post/<int:id>', views.PostDetail.as_view(), name='post_detail'),

    path('static/<int:id>', views.StaticDetail.as_view(), name='static_detail'),
    path('json/', views.formatJson, name='json'),

    path('application', views.ApplicationForm.as_view(), name='application_form'),
    path('contact', views.ContactPage.as_view(), name='contact_view'),

    path('person/', views.PersonList.as_view(), name='person_list'),
    path('person/<int:id>', views.PersonDetail.as_view(), name='person_detail'),

    path('regions/', views.RegionsList.as_view(), name="regions-list"),

    path('organization/', views.OrganizationList.as_view(), name='organization_list'),
    path('organization/<int:id>', views.OrganizationDetail.as_view(), name='organization_detail'),

    path('event/', views.EventList.as_view(), name='event_list'),
    path('event/<int:id>', views.EventDetail.as_view(), name='event_detail'),

    path('media/', views.MediaTemplate.as_view(), name='media_list'),

    path('media/items/', views.MediaGalleryList.as_view(), name='media_gallery_list'),
    path('media/items/<int:id>', views.MediaGalleryDetail.as_view(), name='media_gallery_detail'),

    path('statistics/', views.StatisticsList.as_view(), name='statistics_template'),
    path('search/', views.SearchTemplateView.as_view(), name='search_template'),

    path('album/', views.AlbumList.as_view(), name='album_list'),
    path('album/<int:id>', views.AlbumDetail.as_view(), name='album_detail'),

]

urlpatterns += [
    path('api/typo-report', views.TypoReportAPI.as_view(), name='typo_report_api'),
]

project/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

from main import views as main_views


handler404 = main_views.NotFoundTemplateView.as_view()

urlpatterns = []

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include("poll.urls", namespace='poll')),
    prefix_default_language=True
)

urlpatterns += [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import datetime

import pytz
from django import urls
from django.core import exceptions as django_core_exceptions
from django.core import validators as django_core_validators
from django.db import models
from django.templatetags.static import static
from django.utils.translation import ugettext_lazy as _lazy, ugettext as _
from django.utils import timezone

from ckeditor import fields as ckeditor_fields
from ckeditor_uploader import fields as ckeditor_uploader_fields
from geoposition import fields as geoposition_fields
from mptt import models as mptt_models
from parler import models as parler_models

from . import managers


# Constants
LIST_EVENT_TYPES = (
    ('event', _lazy('Event')),
    ('exhibition', _lazy('Exhibition')),
)

LIST_REGIONS = (
    ('andijan', _lazy("Andijan")),
    ('bukhara', _lazy("Bukhara")),
    ('fergana', _lazy("Fergana")),
    ('jizzakh', _lazy("Jizzakh")),
    ('karakalpakstan', _lazy("Karakalpakstan")),
    ('kashkadarya', _lazy("Kashkadarya")),
    ('khorezm', _lazy("Khorezm")),
    ('namangan', _lazy("Namangan")),
    ('navoi', _lazy("Navoi")),
    ('samarkand', _lazy("Samarkand")),
    ('surkhandarya', _lazy("Surkhandarya")),
    ('syrdarya', _lazy("Syrdarya")),
    ('tashkent_city', _lazy("Tashkent city")),
    ('tashkent_region', _lazy("Tashkent region")),
)


# Mixins
class ViewCountMixin(models.Model):
    view_count = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        abstract = True


class OrderMixin(models.Model):
    order = models.PositiveIntegerField(default=0, blank=False, null=False, editable=False)

    class Meta:
        abstract = True
        ordering = ['order']


class AddedUpdatedDateTimeMixin(models.Model):
    time_added = models.DateTimeField(auto_now_add=True, editable=False, null=True)
    time_updated = models.DateTimeField(auto_now=True, editable=False, null=True)

    class Meta:
        abstract = True


class AddedUpdatedEditableDateTimeMixin(models.Model):
    time_added = models.DateTimeField(auto_now_add=True, editable=True)
    time_updated = models.DateTimeField(auto_now=True, editable=True)

    class Meta:
        abstract = True


# Models

class Banner(OrderMixin, parler_models.TranslatableModel, AddedUpdatedDateTimeMixin):
    translations = parler_models.TranslatedFields(
        title=models.CharField(max_length=255, null=True, blank=True),
        link=models.CharField(max_length=1000, null=True, blank=True),
    )
    image = models.FileField(upload_to="uploads/banner/")

    class Meta:
        ordering = ['order']
        verbose_name = _lazy("Banner")
        verbose_name_plural = _lazy("Banners")

    def __str__(self): return f"{ self.safe_translation_getter('title', self.id) }"


class Menu(mptt_models.MPTTModel, parler_models.TranslatableModel):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, null=True, blank=True)
    translations = parler_models.TranslatedFields(
        name=models.CharField(blank=False, max_length=128),
        link=models.CharField(blank=True, null=True, max_length=128)
    )
    display_in_main_menu = models.BooleanField(default=False)
    objects = managers.CustomMpttManager()

    def __str__(self):
        return self.safe_translation_getter('name', any_language=True) or ''

    class Meta:
        verbose_name = _lazy("Menu item")
        verbose_name_plural = _lazy("Menu items")


class Event(ViewCountMixin, parler_models.TranslatableModel, AddedUpdatedDateTimeMixin):
    translations = parler_models.TranslatedFields(
        title=models.CharField(max_length=255),
        description=models.CharField(max_length=255),
        content=ckeditor_uploader_fields.RichTextUploadingField(),
        note=models.CharField(max_length=255, null=True, blank=True),
        address=models.CharField(max_length=500, null=True),
        organizer=models.CharField(max_length=255, null=True, blank=True),
    )
    image = models.ImageField(upload_to="uploads/event/%Y/%m/%d", default="defaults/event.png")
    event_type = models.CharField(max_length=255, choices=LIST_EVENT_TYPES)

    price = models.IntegerField(null=True, blank=True)
    location = geoposition_fields.GeopositionField(null=True)

    start_date = models.DateTimeField(editable=True, null=True)
    end_date = models.DateTimeField(editable=True, null=True)

    class Meta:
        ordering = ['start_date']
        verbose_name = _lazy("Event")
        verbose_name_plural = _lazy("Events")

    def __str__(self): return f"{ self.safe_translation_getter('title', str(self.id)) }"

    def get_absolute_url(self): return urls.reverse('event_detail', args=[self.id])


class EventOrder(AddedUpdatedDateTimeMixin):
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, null=True)

    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    people_count = models.PositiveSmallIntegerField()
    description = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = _lazy("Event order")
        verbose_name_plural = _lazy("Event orders")

    def __str__(self): return f"{ self.event.safe_translation_getter('title', str(self.id)) }"


class SiteSettings(parler_models.TranslatableModel):
    translations = parler_models.TranslatedFields(
        event_contact_info=ckeditor_fields.RichTextField(config_name='basic', null=True),
        address=models.CharField(max_length=255, null=True),
        email=models.EmailField(null=True),
        tel=models.CharField(max_length=255, null=True),
        work_hours=models.CharField(max_length=255, null=True)
    )

    logo = models.ImageField(upload_to="uploads/logo/", null=True)
    phone_number = models.CharField(max_length=255)

    facebook_link = models.URLField(null=True)
    instagram_link = models.URLField(null=True)
    twitter_link = models.URLField(null=True)
    telegram_link = models.URLField(null=True)
    youtube_link = models.URLField(null=True)

    statistics_accepted = models.PositiveIntegerField(null=True)
    statistics_on_process = models.PositiveIntegerField(null=True)
    statistics_solved = models.PositiveIntegerField(null=True)
    statistics_not_solved = models.PositiveIntegerField(null=True)

    email_receiver = models.CharField(max_length=255, null=True)
    email_sender_address = models.EmailField(null=True)
    email_sender_password = models.CharField(max_length=255, null=True)

    class Meta:
        verbose_name = _lazy("Site settings")
        verbose_name_plural = _lazy("Site settings")

    def __str__(self): return _("Site setting")


# Working
class Person(ViewCountMixin, OrderMixin, parler_models.TranslatableModel, AddedUpdatedDateTimeMixin):
    translations = parler_models.TranslatedFields(
        full_name=models.CharField(max_length=255, null=True, blank=True),
        position=models.CharField(max_length=255),
        admission_days=models.CharField(max_length=255, null=True, blank=True),
        description=ckeditor_uploader_fields.RichTextUploadingField(null=True, blank=True),
        professional_history=ckeditor_uploader_fields.RichTextUploadingField(null=True, blank=True),
    )
    image = models.ImageField(upload_to="uploads/person/%Y/%m/%d/", null=True, blank=True)

    phone_number = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    is_vacant = models.BooleanField(default=False)
    not_primary_staff = models.BooleanField(default=True)

    class Meta:
        verbose_name = _lazy("Person")
        verbose_name_plural = _lazy("Persons")

    def __str__(self): return self.safe_translation_getter('position', self.id)

    def clean(self):
        super().clean()

        if not self.is_vacant:
            non_vacant_required_fields = [
                'full_name',
                'position',
                'phone_number',
                'email',
            ]

            for field in non_vacant_required_fields:
                if not getattr(self, field, False):
                    raise django_core_exceptions.ValidationError({
                        field: _lazy("Required to fill field")
                    })
        else:
            non_vacant_required_fields = [
                'position',
            ]

            for field in non_vacant_required_fields:
                if not getattr(self, field, False):
                    raise django_core_exceptions.ValidationError({
                        field: _lazy("Required to fill field")
                    })

    def get_absolute_url(self): return urls.reverse('person_detail', args=[self.id])

    def resolve_image(self):
        return self.image.url if (self.image and (not self.is_vacant)) else static('../static/custom/img/person.jpg')


class Static(ViewCountMixin, parler_models.TranslatableModel, AddedUpdatedDateTimeMixin):
    translations = parler_models.TranslatedFields(
        title=models.CharField(max_length=255),
        content=ckeditor_uploader_fields.RichTextUploadingField(null=True, blank=True),
    )

    image = models.ImageField(upload_to='uploads/static/%Y/%m/%d/', null=True, blank=True)

    class Meta:
        verbose_name = _lazy("Static page")
        verbose_name_plural = _lazy("Static pages")

    def clean(self):
        super().clean()
        if not self.title and not self.content:
            raise django_core_exceptions.ValidationError({
                'title': _lazy('Even one of title or content should have a value.'),
                'content': _lazy('Even one of title or content should have a value.'),
            })

    def __str__(self): return f"{ self.safe_translation_getter('title') if self.safe_translation_getter('title') else self.id }"


class PostCategory(OrderMixin, parler_models.TranslatableModel, mptt_models.MPTTModel, AddedUpdatedDateTimeMixin):

templates/pages/album/detail.html
{% extends "base.html" %}
{% load i18n static %}


{% block title %}{{ album.title }}{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'custom/plugins/jquery.fancybox/jquery.fancybox.min.css' %}">

    <style>
        .play__video {
            width: 100%;
            height: 100%;
        }

        .play__video::before {
            position: absolute;
            z-index: 1;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background-color: #fff;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            color: var(--second-color);
            padding: 17.5px 21px;
            box-shadow: 0px 0px 5px 4px #ffffff;
        }

        .play__video::after {
            content: '';
            width: 10px;
            height: 10px;
            border-radius: 50%;
            background-color: var(--main-color);
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            position: absolute;
            transform-origin: center;
            animation: burn 3s linear infinite;
        }

        audio {
            width: 100%;
        }

        .no_hover {
            display: block;
            height: 210px;
        }
        .no_hover > img {
            height: 100%;
            object-fit: cover;
            object-position: center;
        }
        @keyframes burn {
            0% {
                width: 10px;
                height: 10px;
                opacity: 1;
            }
            25% {
                width: 25px;
                height: 25px;
                opacity: .8;
            }
            50% {
                width: 50px;
                height: 50px;
                opacity: .6;
            }
            75% {
                width: 75px;
                height: 75px;
                opacity: .4;
            }
            100% {
                width: 85px;
                height: 85px;
                opacity: .0;
            }
        }

        @media (max-width: 767px) {
            .media-title {
                margin-top: 10px;
            }
        }
    </style>
{% endblock %}

{% block js %}
    <script src="{% static 'custom/plugins/jquery.fancybox/jquery.fancybox.min.js' %}"></script>

    <script>
        $('img.fancybox').wrap(function () {
            return "<a href='" + this.attributes['src'].value + "' data-fancybox='gallery-1'></a>";
        });
        $('img.fancybox-gallery-item').wrap(function () {
            return "<a class='no_hover d-inline-block' href='" + this.attributes['src'].value + "' data-fancybox='gallery-2' data-caption='" + this.attributes['data-caption'].value + "'></a>";
        });
        $('img.youtube-thumb').wrap(function () {
            return "<a href='" + this.attributes['data-video-url'].value + "' class='position-relative fa fa-play play__video d-block' data-fancybox='gallery-3'></a>";
        });
        $('video.youtube-thumb').wrap(function () {
            return "<a href='" + this.attributes['data-video-url'].value + "' class='position-relative fa fa-play play__video d-block' data-fancybox='gallery-3'></a>";
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-12">
                <img src="{{ album.albumimage_set.all.0.image.url }}" alt="{{ album.title }}" class="fancybox text-center img-fluid" style="border-radius: 4px"/>
            </div>
            <div class="col-lg-8 col-md-8 col-12">
                <h3 class="mb-3 mt-3 mt-sm-3">{{ album.title }}</h3>
                <h6 style="color: rgba(169,169,169,0.75); margin: 0;">

                    <i class="fa fa-calendar"></i> {{ album.time_added|date:"d / M / Y H:i" }} |

                    <i class="fa fa-tag"></i> {{ album.get_event_type_display }} |
                    <i class="fa fa-globe"></i> {{ album.get_region_display }} |
                    <i class="fa fa-eye"></i> {{ album.view_count }}

                </h6>

                <h6 style="color: rgba(169,169,169,0.75); margin: 7px 0 0 0;">
                    <i class="fas fa-map-marked-alt"></i> {{ album.place }}
                </h6>
                <div><p>{{ album.description|safe }}</p></div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <hr />
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="photo">
                    <div class="row">

                        {% for album_image in album.albumimage_set.all %}
                            {% if album_image.image and album_image.image.url %}
                                <div class="col-lg-4 col-md-6 col-12 my-2 text-center">
                                    <img src="{{ album_image.image.url }}" alt="{{ album_image.title }}" class="fancybox-gallery-item" {% if album_image.title %} data-caption="{{ album_image.title }}" {% else %} data-caption=" " {% endif %} style="border-radius: 4px"/>
                                </div>
                            {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/pages/album/list.html
{% extends "base.html" %}
{% load i18n static %}


{% block title %}{% trans 'Albums' %}{% endblock %}

{% block css %}
    <style>
        .exhibhition-one__bottom-left span:nth-child(2):before {
            display: none;
            content: "";
        }

        .exhibhition-one__bottom-left {
            flex-direction: row;
        }

        .exhibhition-one__bottom-left span:nth-child(2) {
            margin-top: 4px;
        }

        span.event-icon {
            position: absolute;
            top: 0;
            left: 0;
            z-index: 1;
            background: orange;
            color: #fff;
            padding: 10px 20px;
        }
   </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-4">
                <div class="title">
                    <h2>{% trans 'Festivals and competitions' %}</h2>
                </div>
            </div>
        </div>

        {% if albums %}
            <div class="row masonary-layout">

                {% for album in albums %}

                    <div class="col-lg-4 col-md-6 col-sm-12 masonary-item wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="000ms">
                        <div class="collection-three__single">
                            <img src="{{ album.albumimage_set.all.0.image.url }}" alt="{{ album.title }}"/>
                            <div class="collection-three__content">
                                <a href="{{ album.get_absolute_url }}" class="collection-three__link"><span class="fa fa-eye"></span></a>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        {% else %}
            <div class="row">

                <div class="col-12 text-center">
                    <i class="far fa-book-reader mb-4" style="font-size: 5em; color: #0B5B80;"></i>
                    <h4 class="text-uppercase" style="font-size: 2em; color:  var(--main-color);">{% trans 'No festivals found' %}</h4>
                </div>

            </div>
        {% endif %}

    </div>
{% endblock %}



{% comment %}
{% extends "base.html" %}
{% load i18n static %}

{% block title %}{% trans 'Albums' %}{% endblock %}

{% block content %}
    <div class="container">

        <div class="row masonary-layout">

            {% for album in albums %}
                <div class="col-lg-4 col-md-6 col-sm-12 masonary-item wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="000ms">
                    <div class="collection-three__single">
                        <img src="{{ album.albumimage_set.all.0.image.url }}" alt="{{ album.title }}"/>
                        <div class="collection-three__content">
                            <a href="{{ album.get_absolute_url }}" class="collection-three__link"><span class="fa fa-eye"></span></a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

    </div>
{% endblock %}
{% endcomment %}